export const UPDATE_LANGUAGE = 'UPDATE_LANGUAGE'

export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES'

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES'
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS'
export const FETCH_CATEGORIES_ERROR = 'FETCH_CATEGORIES_ERROR'

export const FETCH_LANGUAGES = 'FETCH_LANGUAGES'
export const FETCH_LANGUAGES_SUCCESS = 'FETCH_LANGUAGES_SUCCESS'
export const FETCH_LANGUAGES_ERROR = 'FETCH_LANGUAGES_ERROR'

export const FETCH_CITIES = 'FETCH_CITIES'
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS'
export const FETCH_CITIES_ERROR = 'FETCH_CITIES_ERROR'

export const FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS'
export const FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR'

export const FETCH_WEEGIE_QUESTIONS = 'FETCH_WEEGIE_QUESTIONS'
export const FETCH_WEEGIE_QUESTIONS_SUCCESS = 'FETCH_WEEGIE_QUESTIONS_SUCCESS'
export const FETCH_WEEGIE_QUESTIONS_ERROR = 'FETCH_WEEGIE_QUESTIONS_ERROR'

export const FETCH_WEEGIE_ANSWERS = 'FETCH_WEEGIE_ANSWERS'
export const FETCH_WEEGIE_ANSWERS_SUCCESS = 'FETCH_WEEGIE_ANSWERS_SUCCESS'
export const FETCH_WEEGIE_ANSWERS_ERROR = 'FETCH_WEEGIE_ANSWERS_ERROR'

export const UPDATE_CITY = 'UPDATE_CITY'
